version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: pet_store_snowflake
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: snowflake_db
    ports:
      - "5434:5432"
    volumes:
      - ./исходные данные:/data:ro
      - ./sql:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d snowflake_db"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
